name 'module-ntp'
version '0.1.0'
source 'git://github.com/module/puppet-module-ntp.git'
author 'module'
license 'Apache License, Version 2.0'
summary 'put a summary here'
description 'put a description here'
project_page 'https://github.com/module/puppet-module-ntp'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
